# Generated by Django 5.0.3 on 2025-03-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250308_1912'),
    ]

    operations = [
        
    ]
