# Generated by Django 5.0.3 on 2024-06-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='dislikes',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='likes',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='shares',
            new_name='share',
        ),
    ]
