# Generated by Django 5.0.3 on 2025-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_interaction_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(max_length=10, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('share', 'Share')], default='like'),
        ),
        ]
