# Generated by Django 5.0.3 on 2025-03-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_interaction_session_id'),
    ]

    operations = [
       migrations.RunSQL(
            sql="""
                CREATE TABLE blog_interaction_new AS SELECT id, session_id, created_at, post_id, user_id, action
                FROM blog_interaction;
                DROP TABLE blog_interaction;
                ALTER TABLE blog_interaction_new RENAME TO blog_interaction;
            """,
            reverse_sql="""
                ALTER TABLE blog_interaction ADD COLUMN like BOOLEAN NOT NULL DEFAULT FALSE;
                ALTER TABLE blog_interaction ADD COLUMN dislike BOOLEAN NOT NULL DEFAULT FALSE;
                ALTER TABLE blog_interaction ADD COLUMN share BOOLEAN NOT NULL DEFAULT FALSE;
            """
        ),
    ]
