# Generated by Django 5.0.3 on 2024-06-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_togglestate_delete_interaction'),
    ]

    operations = [
    ]
