# Generated by Django 5.0.3 on 2025-03-13 17:04

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250312_2055'),
    ]

    operations = [
         migrations.AddField(
            model_name="interaction",
            name="action",
            field=models.CharField(max_length=20, default="like"),  # Provide a default value to avoid errors
        ),
    ]
