# Generated by Django 5.0.3 on 2025-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20250313_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('share', 'Share')], default='like', max_length=10),
        ),
    ]
