# Generated by Django 5.0.3 on 2024-06-12 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240612_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='togglestate',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
