# Generated by Django 5.0.3 on 2025-03-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_interaction_session_id_interaction_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='session',
            new_name='session_id',
        ),
    ]
