# Generated by Django 5.0.3 on 2024-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_interaction_delete_togglestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
