# Generated by Django 5.0.3 on 2024-07-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_interaction_dislike_alter_interaction_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='blog.post'),
        ),
    ]
