# Generated by Django 5.0.3 on 2024-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_interaction_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
