# Generated by Django 5.0.3 on 2024-07-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_interaction_session_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('post', 'user_id', 'session_id')},
        ),
    ]
