# Generated by Django 5.0.3 on 2024-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_interaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('post', 'session_id')},
        ),
        migrations.AlterField(
            model_name='interaction',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
