# Generated by Django 5.0.3 on 2025-02-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
