# Generated by Django 5.0.3 on 2025-02-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
