# Generated by Django 5.0.3 on 2025-03-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_adunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='adunit',
            name='cost_per_impression',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=10),
        ),
        migrations.AddField(
            model_name='adunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
